src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FormationRepository;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[ORM\Table(name: "produit")]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacity = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?User $speaker = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'formationsCreatedBy')]
    private ?User $createdBy = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $startDateTime = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endDateTime = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_file_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSpeaker(): ?User
    {
        return $this->speaker;
    }

    public function setSpeaker(?User $speaker): self
    {
        $this->speaker = $speaker;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDateTime(): ?\DateTimeImmutable
    {
        return $this->startDateTime;
    }

    public function setStartDateTime(?\DateTimeImmutable $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    public function getEndDateTime(): ?\DateTimeImmutable
    {
        return $this->endDateTime;
    }

    public function setEndDateTime(?\DateTimeImmutable $endDateTime): self
    {
        $this->endDateTime = $endDateTime;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->image_file_name;
    }

    public function setImageFileName(?string $image_file_name): self
    {
        $this->image_file_name = $image_file_name;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('capacity')
            ->add('price')
            ->add('createdAt')
            ->add('startDate')
            ->add('endDate')
            ->add('description')
            ->add('speaker')
            ->add('createdBy')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use TCPDF;
use DateTimeImmutable;
use App\Entity\Formation;
use App\Form\Formation1Type;
use App\Services\ImageUploaderHelper;
use App\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/produit')]
class FormationController extends AbstractController
{
    #[Route('/pdf/{id}', name: 'app_formation_pdf', methods: ['GET'])]
    public function pdf(Formation $produit): Response
    {
        $pdf = new TCPDF();

        $left_column = '<img src="images/fcpro.jpg">' . 'Tarif : ' . $produit->getPrice() . ' €' . '<br><br>' . 'Places : ' . $produit->getCapacity();
        $right_column = '<b><u>Description de la produit : </u></b><br><br>' . $produit->getDescription() . '<br><br><br>' . '<b><u>Contenu de la produit : </u></b>' . $produit->getContent();
        $y = $pdf->getY();
        $middle = $pdf->getPageWidth() / 2;
        $name = '<b><i>' . $produit->getName() . '</i></b>';

        $pdf->SetTitle($produit->getName());
        $pdf->setCellPaddings(1, 1, 1, 1);
        $pdf->setCellMargins(1, 1, 1, 1);

        $pdf->AddPage();

        $pdf->setXY(10, 1);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, 'Date de création : 01/01/2023', 0, 0, 1, true, 'J', true);

        $pdf->setXY($middle, 1);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, 'Date de mise à jour : 01/01/2023', 0, 0, 1, true, 'J', true);

        $pdf->setXY($middle-30, 15);
        $pdf->SetFont('helvetica', '', 18);
        $pdf->SetTextColor(1, 14, 51);
        $pdf->SetFillColor(212, 225, 237);
        $pdf->writeHTMLCell(125, '', '', $y, $name, 0, 0, 1, true, 'J', true);

        $pdf->SetFillColor(234, 232, 232);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->setXY(10, 15);
        $pdf->writeHTMLCell(60, '', '', $y, $left_column, 0, 0, 1, true, 'J', true);

        $pdf->SetFont('helvetica', '', 9);
        $pdf->setXY($middle-30, 30);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, $right_column, 0, 0, 1, true, 'J', true);


        return $pdf->Output('fcpro-produit-' . $produit->getId() . '.pdf', 'I');
    }

    #[Route('/futur', name: 'app_formation_futur', methods: ['GET'])]
    public function futur(FormationRepository $formationRepository): Response
    {
        $formationsPerThree = array();

        $produits = $formationRepository->findAllInTheFuture();

        $i = 0;
        $j = 1;
        foreach ($produits as $produit){
            $i++;
            if($i>3){
            $j++; $i=1;
            }
        $formationsPerThree[$j][$i] = $produit;
        }
        dump($produit);
        dump($formationsPerThree);

        return $this->render('produit/futur.html.twig', [
            'produits' => $formationsPerThree,
        ]);
    }

    #[Route('/{id}/duplicate', name: 'app_formation_duplicate', methods: ['GET', 'POST'])]
    public function duplicate(Request $request, FormationRepository $formationRepository, TranslatorInterface $translator, Formation $produit): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $formation2 = new Formation();
        $formation2->setCreatedAt($produit->getCreatedAt());
        $formation2->setCreatedBy($produit->getCreatedBy());
        $formation2->setContent($produit->getContent());
        $formation2->setDescription($produit->getDescription());

        $formation2->setCapacity($produit->getCapacity());
        $formation2->setStartDateTime($produit->getStartDateTime());
        $formation2->setEndDateTime($produit->getEndDateTime());
        $formation2->setImageFileName($produit->getImageFileName());
        $formation2->setName($produit->getName());
        $formation2->setPrice($produit->getPrice());

        $formationRepository->save($formation2, true);
        $this->addFlash('success', $translator->trans('The produit is copied'));

        return $this->redirectToRoute('app_formation_index');
    }

    /* #[Route('/futur', name: 'app_formation_futur', methods: ['GET'])]
    public function futur(FormationRepository $formationRepository): Response
    {
        return $this->render('produit/futur.html.twig', [
            'produits' => $formationRepository->findAllInTheFuture(),
        ]);
    }
    */

    #[Route('/catalog', name: 'app_formation_catalog', methods: ['GET'])]
    public function catalog(FormationRepository $formationRepository): Response
    {
        return $this->render('produit/catalog.html.twig', [
            'produits' => $formationRepository->findAllInTheFuture(),
        ]);
    }

    #[Route('/', name: 'app_formation_index', methods: ['GET'])]
    public function index(FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        return $this->render('produit/index.html.twig', [
            'produits' => $formationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_formation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ImageUploaderHelper $imageUploaderHelper, FormationRepository $formationRepository, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $produit = new Formation();
        $produit->setCreatedAt(new DateTimeImmutable());
        $produit->setCreatedBy($this->getUser());

        $form = $this->createForm(Formation1Type::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $errorMessage = $imageUploaderHelper->uploadImage($form, $produit);
            if (!empty($errorMessage)) {
                $this->addFlash ('danger', $translator->trans('An error has occured: ') . $errorMessage);
            }
            $formationRepository->save($produit, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_show', methods: ['GET'])]
    public function show(Formation $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ImageUploaderHelper $imageUploaderHelper, FormationRepository $formationRepository, Formation $produit, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $form = $this->createForm(Formation1Type::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $errorMessage = $imageUploaderHelper->uploadImage($form, $produit);
            if (!empty($errorMessage)) {
                $this->addFlash ('danger', $translator->trans('An error has occured: ') . $errorMessage);
            }
            $formationRepository->save($produit, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $produit, FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) 
        {
            $formationRepository->remove($produit, true);
        }

        return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_delete', {'id': produit.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette produit ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger btn-sm mt-2"><i class="fa-solid fa-trash"></i></button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form.imageFileName) }} #}

    <div class="row">
        <div>
            {{ form_row(form.name) }}
        </div>
        <div>
            {{ form_row(form.description) }}
        </div>
        <div class="col">
            {{ form_row(form.price) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <img width="150" height="150" src="{{ asset('uploads/images/' ~ produit.imageFileName) }}">
        </div>
        <div class="col">
            {{ form_row(form.image) }}
        </div>
    </div>

    <button class="btn btn-primary mt-3">{{ button_label|default('Créer') }}</button>
    <a class="btn btn-secondary mt-3" href="{{ path('app_formation_index') }}">Revenir à la liste</a>
{{ form_end(form) }}

templates/formation/catalog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue des produits{% endblock %}

{% block body %}
<h1>Catalogue des produits</h1>
<table class='table'>
    {% for produit in produits %}
    <td>
        <div class="card" style="width: 15rem;">
            <img src="{{ asset('uploads/images/' ~ produit.imageFileName) }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ produit.name }}</h5>
                <p class="card-text">{{ produit.content|raw }}</p>
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvas-{{ produit.id }}" role="button"
                    aria-controls="offcanvasExample">
                    Détails
                </a>
                <div class="btn btn-secondary">PDF</div>
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-{{ produit.id }}"
                    aria-labelledby="offcanvasExampleLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvas-{{ produit.name }}">{{ produit.name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <div align='center'>
                            <strong> Dates : </strong>{{ produit.startDateTime ? produit.startDateTime|date('d/m/Y')
                            : '' }} - {{ produit.endDateTime ? produit.endDateTime|date('d/m/Y') : '' }}<br>
                            <hr>
                            <strong> Tarif :</strong> {{ produit.price }}€<br>
                            <hr>
                            <strong> Capacité :</strong> {{ produit.capacity }} personnes.<br>
                            <hr>
                            <strong> Contenu :</strong> {{ produit.content|raw }}<br>
                            <hr>
                            <strong> Description :</strong> {{ produit.description }}<br>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    <td>


        {% else %}
        <div class="card" aria-hidden="true">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title placeholder-glow">
                    <span class="placeholder col-6"></span>
                </h5>
                <p class="card-text placeholder-glow">
                    <span class="placeholder col-7"></span>
                    <span class="placeholder col-4"></span>
                    <span class="placeholder col-4"></span>
                    <span class="placeholder col-6"></span>
                    <span class="placeholder col-8"></span>
                </p>
                <a class="btn btn-primary disabled placeholder col-6"></a>
            </div>
        </div>
        {% endfor %}
</table>
{% endblock %}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Edit Formation</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/formation/futur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue des produits{% endblock %}

{% block body %}
    <h1>Formation index</h1>

  <div id="carouselExample" class="carousel carousel-dark slide">
        <div class="carousel-inner">
            {% set i = 0 %}
            {% for formationsPerThree in produits %}
            {% set i = i + 1 %}
                <div class="carousel-item {% if i == 1 %} active {% endif %}">
                    <div class="row">
                    <div class="col">
                        <div class="card" style="width: 14rem;">
                            <img src="{{ asset('uploads/images/' ~ formationsPerThree[1].imageFilename) }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ formationsPerThree[1].name }}</h5>
                                <p class="card-text">{{ formationsPerThree[1].content }}</p>
                                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvas-{{ formationsPerThree[1].id }}" role="button" aria-controls="offcanvasExample">
                                    Détails
                                    </a>
                                    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-{{ formationsPerThree[1].id }}" aria-labelledby="offcanvasExampleLabel">
                                    <div class="offcanvas-header">
                                        <h5 class="offcanvas-title" id="offcanvas-{{ formationsPerThree[1].name }}">{{ formationsPerThree[1].name }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                    </div>
                                    <div class="offcanvas-body">
                                        <div align='center'>
                                            <strong> Dates : </strong>{{ formationsPerThree[1].startDateTime ? formationsPerThree[1].startDateTime|date('d/m/Y') : '' }} - {{ formationsPerThree[1].endDateTime ? formationsPerThree[1].endDateTime|date('d/m/Y') : '' }}<br><hr>
                                            <strong> Tarif :</strong> {{ formationsPerThree[1].price }}€<br><hr>
                                            <strong> Capacité :</strong> {{ formationsPerThree[1].capacity }} personnes.<br><hr>
                                            <strong> Contenu :</strong> {{ formationsPerThree[1].content }}<br><hr>
                                            <strong> Description :</strong> {{ formationsPerThree[1].description }}<br><hr>
                                            
                                        </div>
                                        <div class="dropdown mt-3">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                            Actions
                                        </button>
                                            <ul align='center' class="dropdown-menu">
                                            
                                                <li><a class="dropdown-item" href="/produit/pdf/{{ formationsPerThree[1].id }}">Installer la fiche PDF</a></li>
                                                <!--<li><a class="dropdown-item" href="#">Something else here</a></li>
                                                <li><a class="dropdown-item" href="#">Action</a></li>-->
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if formationsPerThree[2] is defined  %}
                        <div class="col">
                            <div class="card" style="width: 14rem;">
                                <img src="{{ asset('uploads/images/' ~ formationsPerThree[2].imageFilename) }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{ formationsPerThree[2].name }}</h5>
                                    <p class="card-text">{{ formationsPerThree[2].content }}</p>
                                    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvas-{{ formationsPerThree[2].id }}" role="button" aria-controls="offcanvasExample">
                                        Détails
                                        </a>
                                        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-{{ formationsPerThree[2].id }}" aria-labelledby="offcanvasExampleLabel">
                                        <div class="offcanvas-header">
                                            <h5 class="offcanvas-title" id="offcanvas-{{ formationsPerThree[2].name }}">{{ formationsPerThree[2].name }}</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                        </div>
                                        <div class="offcanvas-body">
                                            <div align='center'>
                                                <strong> Dates : </strong>{{ formationsPerThree[2].startDateTime ? formationsPerThree[2].startDateTime|date('d/m/Y') : '' }} - {{ formationsPerThree[2].endDateTime ? formationsPerThree[2].endDateTime|date('d/m/Y') : '' }}<br><hr>
                                                <strong> Tarif :</strong> {{ formationsPerThree[2].price }}€<br><hr>
                                                <strong> Capacité :</strong> {{ formationsPerThree[2].capacity }} personnes.<br><hr>
                                                <strong> Contenu :</strong> {{ formationsPerThree[2].content }}<br><hr>
                                                <strong> Description :</strong> {{ formationsPerThree[2].description }}<br><hr>
                                            </div>
                                            <div class="dropdown mt-3">
                                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                                    Actions
                                                </button>
                                                <ul align='center' class="dropdown-menu">
                                                
                                                    <li><a class="dropdown-item" href="/produit/pdf/{{ formationsPerThree[2].id }}">Installer la fiche PDF</a></li>
                                                    <!--<li><a class="dropdown-item" href="#">Something else here</a></li>
                                                    <li><a class="dropdown-item" href="#">Action</a></li>-->
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    {% if formationsPerThree[3] is defined  %}
                    <div class="col">
                        <div class="card" style="width: 14rem;">
                            <img src="{{ asset('uploads/images/' ~ formationsPerThree[3].imageFilename) }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ formationsPerThree[3].name }}</h5>
                                <p class="card-text">{{ formationsPerThree[3].content }}</p>
                                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvas-{{ formationsPerThree[3].id }}" role="button" aria-controls="offcanvasExample">
                                    Détails
                                    </a>
                                    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-{{ formationsPerThree[3].id }}" aria-labelledby="offcanvasExampleLabel">
                                    <div class="offcanvas-header">
                                        <h5 class="offcanvas-title" id="offcanvas-{{ formationsPerThree[3].name }}">{{ formationsPerThree[3].name }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                    </div>
                                    <div class="offcanvas-body">
                                        <div align='center'>
                                            <strong> Dates : </strong>{{ formationsPerThree[3].startDateTime ? formationsPerThree[3].startDateTime|date('d/m/Y') : '' }} - {{ formationsPerThree[3].endDateTime ? formationsPerThree[3].endDateTime|date('d/m/Y') : '' }}<br><hr>
                                            <strong> Tarif :</strong> {{ formationsPerThree[3].price }}€<br><hr>
                                            <strong> Capacité :</strong> {{ formationsPerThree[3].capacity }} personnes.<br><hr>
                                            <strong> Contenu :</strong> {{ formationsPerThree[3].content }}<br><hr>
                                            <strong> Description :</strong> {{ formationsPerThree[3].description }}<br><hr>
                                            
                                        </div>
                                        <div class="dropdown mt-3">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                            Actions
                                        </button>
                                            <ul align='center' class="dropdown-menu">
                                            
                                                <li><a class="dropdown-item" href="/produit/pdf/{{ formationsPerThree[3].id }}">Installer la fiche PDF</a></li>
                                                <!--<li><a class="dropdown-item" href="#">Something else here</a></li>
                                                <li><a class="dropdown-item" href="#">Action</a></li>-->
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  
                </div>
                </div>
                {% endif %}
            {% endfor %}

        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
</div>
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations{% endblock %}

{% block body %}
    <h1>Liste des produits</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                {#<th>Content</th>#}
                {#<th>Capacité</th>#}
                {#<th>Tarif</th>#}
                {#<th>Date de création</th>#}
                {#<th>Description</th>#}
                {#<th>Date de début</th>#}
                {#<th>Date de fin</th>#}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.name }}</td>
                {#<td>{{ produit.content }}</td>#}
                {#<td>{{ produit.capacity }}</td>#}
                {#<td>{{ produit.price }}</td>#}
                {#<td>{{ produit.createdAt ? produit.createdAt|date('Y-m-d H:i:s') : '' }}</td>#}
                {#<td>{{ produit.description }}</td>#}
                {#<td>{{ produit.startDateTime ? produit.startDateTime|date('Y-m-d H:i:s') : '' }}</td>#}
                {#<td>{{ produit.endDateTime ? produit.endDateTime|date('Y-m-d H:i:s') : '' }}</td>#}
                <td>
                    <a class="btn btn-secondary btn-sm" href="{{ path('app_formation_show', {'id': produit.id}) }}"><i class="fa-solid fa-eye"></i></a>
                    <a class="btn btn-warning btn-sm" href="{{ path('app_formation_edit', {'id': produit.id}) }}"><i class="fa-solid fa-pen"></i></a>
                    <a class="btn btn-secondary btn-sm" href="{{ path('app_formation_duplicate', {'id': produit.id}) }}"><i class="fa-solid fa-copy"></i></a>
                    {{ include('produit/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Il n'y a aucune produit !</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_formation_new') }}"><i class="fa-solid fa-plus"></i> Nouvelle produit</a>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Nouveaux produits</h1>

    {{ include('produit/_form.html.twig') }}

{% endblock %}